PTKidsBITVX.motorWrite(Motor_Write.Motor_1, 100)
basic.pause(500)
PTKidsBITVX.motorWrite(Motor_Write.Motor_2, -100)
basic.pause(500)
PTKidsBITVX.motorStop()
basic.pause(500)
PTKidsBITVX.Turn(_Turn.Left, 100)
basic.pause(500)
PTKidsBITVX.Spin(_Spin.Right, 100)
basic.pause(500)
PTKidsBITVX.servoWrite(Servo_Write.S0, 180)
basic.pause(500)
PTKidsBITVX.servoWrite(Servo_Write.S0, 90)
basic.forever(function () {
    basic.showNumber(PTKidsBITVX.ADCRead(ADC_Read.ADC0))
})